//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Resource()
        {
            this.Tasks = new HashSet<Task>();
        }


        //[System.ComponentModel.Browsable(false)]
        public int ID { get; set; }
        public string Ten { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string VaiTro { get; set; }
        public string SoDienThoai { get; set; }
        public string Mail { get; set; }

        [System.ComponentModel.Browsable(false)]
        public Nullable<int> IDTask { get; set; }

        [System.ComponentModel.Browsable(false)]
        public virtual Task Task { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        [System.ComponentModel.Browsable(false)]
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
