//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.Resources = new HashSet<Resource>();
        }
    
        public int ID { get; set; }

        [System.ComponentModel.Browsable(false)]
        public Nullable<int> IDProject { get; set; }

        //[System.ComponentModel.Browsable(false)]
        public Nullable<int> IDResource { get; set; }
        public string TenCongViec { get; set; }
        public string MoTa { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }


        [System.ComponentModel.Browsable(false)]
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        [System.ComponentModel.Browsable(false)]
        public virtual ICollection<Resource> Resources { get; set; }

        [System.ComponentModel.Browsable(false)]
        public virtual Resource Resource { get; set; }
    }
}
